name: Build APK for FUTBConnect

on: 
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v3

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'

     - name: Install Buildozer & dependencies
       run: |
         sudo apt update
         sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools git build-essential libncurses5-dev libstdc++6 zlib1g zlib1g-dev libffi-dev libssl-dev libsqlite3-dev libbz2-dev
         pip install --upgrade pip Cython virtualenv
         pip install buildozer

     - name: Install Android Build Tools
       run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-*.zip -d temp-tools
          mkdir -p cmdline-tools/latest
          mv temp-tools/cmdline-tools/* cmdline-tools/latest/
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;34.0.0" "platforms;android-34" "platform-tools"

     - name: Set environment variables
       run: |
         echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
         echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_ENV

     - name: Initialize Buildozer project
       run: |
         unzip FUTBConnect_Kivy_BuildReady.zip -d futbconnect
         cd futbconnect
         buildozer init || true

     - name: Build APK
       run: |
         cd futbconnect
         buildozer android debug

     - name: Upload APK Artifact
       uses: actions/upload-artifact@v4
       with:
         name: futbconnect-apk
         path: futbconnect/bin/*.apk


